blueprint:
  name: Lamp with NFC Tag
  description: Toggles a Lamp via an NFC-Tag
  domain: automation
  input:
    nfc-tag:
      name: NFC-Tag
      description: The NFC-Tag that will toggle the Lamp
      selector:
        entity:
          filter:
            - domain: tag
          multiple: true
    lamp:
      name: Lamp
      description: The Lamp that will be toggled via Tag
      selector:
        entity:
          filter:
            - domain: light

triggers:
  - trigger: tag
    tag_id: !input nfc_tag
actions:
  - action: light.toggle
    target:
      entity_id: !input lamp
    data: { }

mode: restart
