blueprint:
  name: Lamp with NFC Tag
  description: Toggles a Lamp via an NFC-Tag
  domain: automation
  input:
    nfc_tags:
      name: NFC-Tag(s)
      description: The NFC-Tag(s) that will toggle the Lamp
      selector:
        entity:
          filter:
            - domain: tag
          multiple: true
    lamp:
      name: Lamp
      description: The Lamp that will be toggled via Tag
      selector:
        entity:
          filter:
            - domain: light

variables:
  nfc_tags: !input 'nfc_tags'
triggers:
  - trigger: event
    event_type: tag_scanned
conditions:
  - '{{ trigger.event.data.tag_id in nfc_tags | map(attribute="tag_id") }}'
actions:
  - action: light.toggle
    target:
      entity_id: !input lamp
    data: { }

mode: restart
